# Paths configuration
[paths]
# Directories for various file types
volcano = /var/www/geoinquire/volcanoes/
type = types/
incoming = temp/incoming/
temp = temp/
version = temp/old/
trash = temp/trash/

# SSL Certificates
# IMPORTANT: DEBUG = True
#These fields are sensitive and should be set in a secure manner.
#            Consider using environment variables or a secure vault for storing these values.
#            The paths below are examples. Make sure to point to the correct certificate files.
crt =  /home/ehernandez/Documentos/P_Website_API/volcano-api-main/server.crt
key =  /home/ehernandez/Documentos/P_Website_API/volcano-api-main/private.key

# Webserver configuration
[webserver]
# Domain and port settings
# Specify the host domain or IP address. If not set, 'localhost' will be used.
# Examples for the host field are provided in the comments.
host = 127.0.0.1
port = 5000
DEBUG = True

# Flask specific configurations
[flask]
# Server name and debug settings
SERVER_NAME = 'localhost:8888'

# Configuración de Flask
#DEBUG = True  # Activa el modo de depuración
#SWAGGER_UI_DOC_EXPANSION = 'none'  # Expandir la documentación de Swagger
#RESTX_VALIDATE = True  # Activar la validación de entradas RESTx
#RESTX_MASK_SWAGGER = False  # Desactivar la máscara de Swagger en RESTx
#RESTX_ERROR_404_HELP = False  # No mostrar ayuda en caso de errores 404 en RESTx

